{
    'name': 'Taller Mecanico - Portal Web',
    'version': '1.0',
    'category': 'Website',
    'summary': 'Portal de clientes y gestión web de citas',
    'description': """
        Añade el acceso web "Mi Cuenta", vistas de autos y agenda de citas para los clientes.
    """,
    'author': 'Tu Nombre',
    'depends': ['taller_mecanico', 'website', 'website_sale', 'usuarios_taller'],
    'data': [
        'views/pages/login.xml',
        'views/pages/registro.xml',
        'views/pages/registro_confirmacion.xml',
        'views/pages/mi_cuenta.xml',
        'views/pages/home.xml',
        'views/pages/servicios.xml',
        'views/pages/contacto.xml',
        'views/pages/cita.xml',
        'views/pages/cita_confirmacion.xml',
        'views/pages/productos.xml',
        'views/pages/carrito.xml',
        'views/pages/confirmacion.xml',
        'views/pages/nosotros.xml',
        'views/pages/preguntas_frecuentes.xml',
        'views/pages/consulta_orden.xml',
        'views/pages/pricing.xml',
        'views/templates.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'taller_mecanico_portal/static/src/scss/_variables.scss',
            'taller_mecanico_portal/static/src/scss/_common.scss',
            'taller_mecanico_portal/static/src/scss/pages/_home.scss',
            'taller_mecanico_portal/static/src/scss/pages/_servicios.scss',
            'taller_mecanico_portal/static/src/scss/pages/_cita.scss',
            'taller_mecanico_portal/static/src/scss/pages/_shop.scss',
            'taller_mecanico_portal/static/src/scss/pages/_portal.scss',
            'taller_mecanico_portal/static/src/js/taller_shop.js',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
