version: '3.8'

services:
  proxy:
    image: nginx:1.27-alpine
    container_name: odoo-proxy
    depends_on:
      - odoo
    ports:
      - "8070:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    restart: always
    networks:
      - edge
      - app

  odoo:
    image: odoo:18
    container_name: odoo18
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    restart: always
    networks:
      - app

volumes:
  odoo-data:

networks:
  edge:
  app: