{
    'name': 'Taller Mecanico',
    'version': '1.0',
    'category': 'Website',
    'summary': 'Sitio web para el taller mecanico',
    'description': """
        Modulo para el sitio web del taller mecanico.
        Incluye paginas estaticas: Inicio, Servicios, Contacto y Formulario de Cita.
    """,
    'author': 'Tu Nombre',
    'depends': ['website', 'stock', 'sale', 'account', 'usuarios_taller', 'contacts', 'hr', 'mail', 'payment_stripe', 'payment_paypal'],
    'external_dependencies': {
        'python': ['requests'],
    },
    'data': [
        'security/ir.model.access.csv',
        'data/product.product.csv',
        'data/stock_init_data.xml',
        'data/demo_data.xml',
        'views/menus.xml',
        'views/vehiculo_views.xml',
        'views/orden_trabajo_views.xml',
        'views/cita_taller_views.xml',
        'views/hr_employee_views.xml',
        'views/res_company_views.xml',
        'views/account_move_views.xml',
        'views/report_invoice_sri.xml',
        'views/pages/login.xml',
        'views/pages/registro.xml',
        'views/pages/registro_confirmacion.xml',
        'views/pages/home.xml',
        'views/pages/servicios.xml',
        'views/pages/contacto.xml',
        'views/pages/cita.xml',
        'views/pages/cita_confirmacion.xml',
        'views/pages/productos.xml',
        'views/pages/carrito.xml',
        'views/pages/confirmacion.xml',
        'views/templates.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'assets': {
        'web.assets_frontend': [
            'taller_mecanico/static/src/css/taller_style.css',
            'taller_mecanico/static/src/js/taller_shop.js',
        ],
    },
}
